import json
from pathlib import Path

CHAT_LOG = Path(__file__).parent / "chat_log.json"

history = []
if CHAT_LOG.exists():
    with open(CHAT_LOG, 'r', encoding='utf-8') as f:
        history = json.load(f)

web_session = [
    {"role": "user", "content": "Привет! Составь подробный отчёт о всей нашей работе."},
    {"role": "assistant", "content": "[Отчёт, план, предложение аватара]"},
    {"role": "user", "content": "А какова сама цель проекта?"},
    {"role": "assistant", "content": "[QASAR — платформа ИИ-компаньона]"},
    {"role": "user", "content": "т.е платформу делаем?"},
    {"role": "assistant", "content": "[Да, экосистема]"},
    {"role": "user", "content": "Думаю надо заняться текстурами в комнате..."},
    {"role": "assistant", "content": "[Предложил Poly Haven, ambientCG]"},
    {"role": "user", "content": "я давал скрин, там яркие цвета..."},
    {"role": "assistant", "content": "[Глянцевый пол, мрамор, освещение]"},
    {"role": "user", "content": "Пока рано код, нужно обсудить дизайн..."},
    {"role": "assistant", "content": "[Реактивные LED, умный HUD, напольная проекция]"},
    {"role": "user", "content": "ну в целом начинаем украшать комнату..."},
    {"role": "assistant", "content": "[QASAR Hub — концепция]"},
    {"role": "user", "content": "Да, неплохо. Давай сделаем ещё транспортёр..."},
    {"role": "assistant", "content": "[Транспортёр — цилиндр-телепорт]"},
    {"role": "user", "content": "а можно ли его сделать как выдвигающаяся из потолка до пола труба..."},
    {"role": "assistant", "content": "[Лучевая колонна]"},
    {"role": "user", "content": "наверно нужен и принимающий порт на полу..."},
    {"role": "assistant", "content": "[Встречные лучи]"},
    {"role": "user", "content": "да и про персонажа, может его сделать в блендер..."},
    {"role": "assistant", "content": "[Риг, анимации, интеграция]"},
    {"role": "user", "content": "Ну проект сложный, так что это надолго..."},
    {"role": "assistant", "content": "[Пошаговый план развития]"},
    {"role": "user", "content": "Давай делать каталогами..."},
    {"role": "assistant", "content": "[Модульная архитектура, структура каталога]"},
    {"role": "user", "content": "ты когда пишешь имя файла floor.js или иное, в скобочках пиши комментарий..."},
    {"role": "assistant", "content": "[Номенклатура, имена объектов]"},
    {"role": "user", "content": "нет, нужно сделать что бы каталог и остальное тоже сохранялись в памяти сессии..."},
    {"role": "assistant", "content": "[Обновил project_context.txt]"},
    {"role": "user", "content": "не спеши. Теперь основной промт изменим..."},
    {"role": "assistant", "content": "[Обсудили дополнения в web_prompt.txt]"},
    {"role": "user", "content": "Яндекс.Диск а ты сможешь от туда прочитать..."},
    {"role": "assistant", "content": "[GitHub — лучшее хранилище]"},
    {"role": "user", "content": "Давай проверим, а гитхаб должен быть открытым профилем?"},
    {"role": "assistant", "content": "[Публичный — да, приватный — нет]"},
    {"role": "user", "content": "https://github.com/mitrofansa/ai-companion/releases промт делай и проверим гитхаб"},
    {"role": "assistant", "content": "[Обновил web_prompt.txt v2.0]"},
    {"role": "user", "content": "(установщик SillyTavern) в project_context.txt, мы же с ним не работаем..."},
    {"role": "assistant", "content": "[Убрал SillyTavern из web_prompt.txt]"},
    {"role": "user", "content": "project_context.txt проверь то же"},
    {"role": "assistant", "content": "[Убрал SillyTavern из project_context.txt]"},
    {"role": "user", "content": "Теперь сразу настроим гит хаб..."},
    {"role": "assistant", "content": "[Инструкция по созданию релиза]"},
    {"role": "user", "content": "[Описание релиза]"},
    {"role": "assistant", "content": "[Текст описания]"},
    {"role": "user", "content": "а остальные файлы не нужны?"},
    {"role": "assistant", "content": "[Список файлов для загрузки]"},
    {"role": "user", "content": "а файлы рабочие не нужно? C:\\Projects\\QASAR"},
    {"role": "assistant", "content": "[Полный список из 12 файлов]"},
    {"role": "user", "content": "Гайд_Память_для_ИИ нужно сменить на английское название?"},
    {"role": "assistant", "content": "[Оставь русское]"},
    {"role": "user", "content": "проверь"},
    {"role": "assistant", "content": "[Релиз опубликован!]"},
    {"role": "user", "content": "да говори, я не знаю как"},
    {"role": "assistant", "content": "[Инструкция по загрузке в репозиторий]"},
    {"role": "user", "content": "я пересоздаю"},
    {"role": "assistant", "content": "[Ок, после пересоздания — загрузи файлы]"},
    {"role": "user", "content": "нужно описание"},
    {"role": "assistant", "content": "[Дал README.md]"},
    {"role": "user", "content": "guide_memory_for_ai.md название сменил на английский"},
    {"role": "user", "content": "assistant.py тоже гружу?"},
    {"role": "assistant", "content": "[Нет, там ключ]"},
    {"role": "user", "content": "проверь"},
    {"role": "assistant", "content": "[Всё на месте]"},
    {"role": "user", "content": "да, наверное, мне просто хочется всё там грамотно заполнить"},
    {"role": "assistant", "content": "[Инструкция по README и релизу]"},
    {"role": "user", "content": "проверь всё"},
    {"role": "assistant", "content": "[Всё готово!]"},
    {"role": "user", "content": "по нашему сохранению всё сохранено? да и как новые сохранения туда попадут?"},
    {"role": "assistant", "content": "[Объяснил процесс]"},
    {"role": "user", "content": "а ты можешь в промт добавить напоминание об сохранении в репозитории и действия мои"},
    {"role": "assistant", "content": "[Обновил web_prompt.txt v2.2]"},
    {"role": "user", "content": "А сделать автообновление никак, для репозитория?"},
    {"role": "assistant", "content": "[Никак, только полуавтоматически]"},
    {"role": "user", "content": "ну в целом готов. Какой план? Ты ищешь текстуры или я?"},
    {"role": "assistant", "content": "[План Этапа 1, список сайтов]"},
    {"role": "user", "content": "Для пола пойдёт? https://ambientcg.com/view?id=Marble002"},
    {"role": "assistant", "content": "[Marble 002 — отлично!]"},
    {"role": "user", "content": "Стены https://ambientcg.com/view?id=Marble001 берём?"},
    {"role": "assistant", "content": "[Marble 001 — отлично!]"},
    {"role": "user", "content": "https://ambientcg.com/view?id=Marble015 такой?"},
    {"role": "assistant", "content": "[Marble 015 — отлично!]"},
    {"role": "user", "content": "нам нужны jpeg? а то там есть и png"},
    {"role": "assistant", "content": "[JPEG — лучше для веба]"},
    {"role": "user", "content": "[Скриншот архива] Там много файлов в архиве, тебе только jpeg нужны?"},
    {"role": "assistant", "content": "[Да, только 3 JPEG из каждого]"},
    {"role": "user", "content": "[Скриншот папки textures] Проверь."},
    {"role": "assistant", "content": "[9 файлов на месте]"},
    {"role": "user", "content": "это отдельные файлы и отдельный каталог?"},
    {"role": "assistant", "content": "[Да, модули в js/]"},
    {"role": "user", "content": "давай файлы и говори куда их положить и как всё запустить."},
    {"role": "assistant", "content": "[Дал floor_01_main.js, walls_01_main.js, ceiling_01_main.js, main.js]"},
    {"role": "user", "content": "сбой управления и старта камеры"},
    {"role": "assistant", "content": "[Исправил main.js]"},
    {"role": "user", "content": "[Скриншоты] стены первая стена изнутри прозрачная, вторая стена покрашена с двух сторон..."},
    {"role": "assistant", "content": "[Исправил стороны на BackSide]"},
    {"role": "user", "content": "[Скриншоты] первую стену крась изнутри, она у тебя прозрачная."},
    {"role": "assistant", "content": "[Крашу BackSide внешнего стекла]"},
    {"role": "user", "content": "нет, стёкла вообще не трогай - это не стена..."},
    {"role": "assistant", "content": "[Стена — отдельный цилиндр]"},
    {"role": "user", "content": "[Скриншот] ты создал новую стену? и она вторая если смотреть изнутри..."},
    {"role": "assistant", "content": "[Понял архитектуру: 4 слоя]"},
    {"role": "user", "content": "А вот внешнее стекло (19.4м) — это и есть стена. Нет не так!..."},
    {"role": "assistant", "content": "[Понял: стены в GLB, стёкла отдельно]"},
    {"role": "user", "content": "[Скриншот] стены прозрачные? )))"},
    {"role": "assistant", "content": "[Перенёс createWalls в колбэк GLB]"},
    {"role": "user", "content": "[Скриншот] мудришь опять."},
    {"role": "assistant", "content": "[Понял, прекращаю. Даю main.js с текстурами на GLB]"},
    {"role": "user", "content": "[Скриншот] ты проёмы покрасил не стой стороны. А стены где?"},
    {"role": "assistant", "content": "[Возвращаю walls_01_main.js с отдельной стеной]"},
    {"role": "user", "content": "А в main.js верни вызов createWalls(scene) на место (до загрузки GLB) это как?"},
    {"role": "assistant", "content": "[Дал полный main.js с createWalls до GLB]"},
    {"role": "user", "content": "[Скриншот] ты опять создал стену? и покрасил её)))..."},
    {"role": "assistant", "content": "[Понял: нужно красить существующую стену в GLB]"},
    {"role": "user", "content": "[Скриншот] зачем ты проёмы красишь то с другой стороны? Где стена?"},
    {"role": "assistant", "content": "[Понял: GLB — единый меш]"},
    {"role": "user", "content": "не проще нам вернутся к блендер, я там натяну текстуры?"},
    {"role": "assistant", "content": "[Да! Blender — лучшее решение]"},
    {"role": "user", "content": "Сделал"},
    {"role": "assistant", "content": "[Убрал модули, дал чистый main.js v0.2.4]"},
    {"role": "user", "content": "[Скриншот] нам ещё нужно добавить в управление вверх и вниз движение..."},
    {"role": "assistant", "content": "[Добавил E/Q в controls.js]"},
    {"role": "user", "content": "можешь добавить в управлении движение при зажатой лкм и w..."},
    {"role": "assistant", "content": "[Добавил ЛКМ+W/S для полёта по взгляду]"},
    {"role": "user", "content": "ты вверх вниз добавил, а горизонтально пропало"},
    {"role": "assistant", "content": "[Исправил: A/D всегда горизонтально]"},
    {"role": "user", "content": "Ну похоже многое делать в блендере проще"},
    {"role": "assistant", "content": "[Согласился, обновил ARCHITECTURE.md]"},
    {"role": "user", "content": "его тоже в репозиторий?"},
    {"role": "assistant", "content": "[Да]"},
    {"role": "user", "content": "а текстуры?"},
    {"role": "assistant", "content": "[Да, загрузи в textures/]"},
    {"role": "user", "content": "а как там создать папку?"},
    {"role": "assistant", "content": "[GitHub создаст папку сам при загрузке файлов]"},
    {"role": "user", "content": "проверь гитхаб"},
    {"role": "assistant", "content": "[Всё на месте, включая textures/]"},
    {"role": "user", "content": "я отдыхать."},
]

existing = {(m["role"], m["content"]) for m in history}
new_msgs = [m for m in web_session if (m["role"], m["content"]) not in existing]
history.extend(new_msgs)

with open(CHAT_LOG, 'w', encoding='utf-8') as f:
    json.dump(history, f, ensure_ascii=False, indent=2)

print(f"✅ Добавлено новых сообщений: {len(new_msgs)}")
print(f"📝 Всего в истории: {len(history)}")